/// <reference types="cypress" />


  context('IMS End-to-End Flow', () => {

  beforeEach(() => {
    cy.viewport(1920, 1080)
    cy.clearCookies()
    cy.clearLocalStorage()
  })

  it('Invoice Creation in Base Currency', () => {

    // 🔐 LOGIN WITH BASIC AUTH
    cy.visit('https://inventory.seebiz.cloud', {
      auth: {
        username: 'admin',
        password: 'Temp123'
      },
      timeout: 60000,
      failOnStatusCode: false
    })

    // LOGIN VIA FORM
    cy.xpath("//input[@id='email']").should('be.visible')
      .type('pirzadahaseeb717+aaa-14@gmail.com')

    cy.xpath("//input[@id='password']")
      .type('Changeme1@3')

    cy.xpath("//button[@id='click_login_button']").click()

    // VERIFY DASHBOARD
    cy.contains('Dashboard', { timeout: 20000 }).should('be.visible')

    // 📦 NAVIGATE TO INVOICE MODULE
    cy.xpath("//button[@id='click_nav_arrow_button']").click()
    cy.xpath("//a[@id='click_invoice_module']").click()
    cy.xpath("//button[@id='Click_Add_New_Item_Adjustment_Button']").click()

    // ➕ ADD CUSTOMER
    cy.xpath("(//div[contains(@class,'indicatorContainer')])[1]").click()
    cy.wait(2000)
    cy.contains("Add New").should('be.visible').click()
    cy.wait(2000)

    // SELECT PREFIX
    cy.xpath("(//div[contains(@class,'searchable-dropdown__control')]//div[contains(@class,'searchable-dropdown__value-container')])[6]").click()
    cy.wait(3000)

    cy.get('div.searchable-dropdown__menu')
      .should('be.visible')
      .contains('Dr.')
      .click()

    // CREATE UNIQUE CUSTOMER
    const uniqueCustomerName = `CUSTOMER-${Date.now()}`
    cy.xpath("//input[@id='firstName']").clear().type(uniqueCustomerName)

    // SAVE CUSTOMER
    cy.xpath("(//div[@class='searchable-dropdown__control css-yk16xz-control'])[6]").click()
    cy.get('#react-select-11-option-0').click()

    cy.xpath("//button[contains(@type,'submit')][normalize-space()='Save']").click()
    cy.get('.toaster-body')
      .should('be.visible')
      .contains('Contact created successfully')

    // ADD NOTE
    cy.xpath("//textarea[@id='note']").type('THIS TEXT IS MANUALLY GENERATED BY THE QA TEAM')

    // ➕ ADD ITEM
    cy.xpath('(//div[@class=" css-tlfecz-indicatorContainer"])[3]').click()
    cy.wait(2000)

    cy.get('.DDTopElement').should('be.visible').contains('Add New').click()

    // IMAGE UPLOAD
    cy.get('input[type="file"]').attachFile('PROFILE.jpg')
    cy.xpath('//button[@id="next-btn"]').contains('Save Original').should('be.visible').click()

    // CREATE UNIQUE ITEM
    const uniqueItemName = `ITEM-${Date.now()}`
    cy.get('#name').clear().type(uniqueItemName)

    cy.xpath('(//input[@class="form-input"])[4]').click()
    cy.contains('kg').should('be.visible').click()
    cy.xpath('//button[@id="Click_generate_item_SKU"]').click()

    cy.xpath('//input[@id="purchaseUnitPrice"]').clear().type('100')
    cy.xpath('//input[@id="salesUnitPrice"]').clear().type('500')
    cy.xpath('//input[@id="warehouses[0].openingStock"]').clear().type('100')
    cy.xpath('//input[@id="openingStockValue"]').clear().type('10')

    cy.wait(2000)

    cy.xpath('(//button[@class="action-buttons--submit next-btn float-left"])[3]').contains('Save').should('be.visible').click()

    cy.xpath('//span[@class="total-price--value float-right mr-1"]').should('be.visible').contains('$500')

    // SAVE FINAL ITEM
    cy.xpath('//button[@type="button"]').contains('Save').should('be.visible').click()
    cy.wait(3000)
    cy.reload(true)
    cy.xpath('(//span[@class="list_items_desc"])[1]', { timeout: 30000 }).should('be.visible').click()

    // MARK ITEM AS SENT
    cy.xpath("//button[normalize-space()='Options']").click()
    cy.get('.checked-menu--dropdown .custom-dropdown-container:visible').contains('Mark as Sent').click()

    cy.reload(true)
    cy.xpath('(//span[@class="list_items_desc"])[1]').click()
    cy.get('.nav_menu > :nth-child(2) > a').click()
    cy.xpath('//button[@class="layout-box--button"]', { timeout: 20000 }).click()
    cy.xpath('//input[@id="amount"]').clear().click().type('500')
    cy.xpath('//button[@type="submit"]', { timeout: 20000 }).contains('Save').should('be.visible').click()
    cy.contains('a', 'Credit Notes').click()
    cy.xpath('//button[@class="layout-box--button"]', { timeout: 20000 }).click()
    cy.xpath("//span[normalize-space()='Add Credit Note']").should('contain.text', 'Add Credit Note')
    cy.xpath("//button[@type='submit' and normalize-space()='Save']")
      .should('be.visible')
      .click()
    cy.xpath("//div[@class='CaretDownButton']//*[name()='svg']").click()
    cy.xpath("//button[@type='submit' and normalize-space()='Mark as Open']").contains('Mark as Open').click()

    cy.xpath("//div[@class='CaretDownButton' and normalize-space()='Actions']")
      .should('be.visible')
      .click()

    cy.xpath("//div[contains(@class,'custom-dropdown-container down')]//span[contains(@class,'custom-dropdown-set')][normalize-space()='Edit']").contains('Edit').click()
    cy.xpath("//button[@type='submit' and normalize-space()='Save']")
      .should('be.visible')
      .click()

    })

  })

