/// <reference types="cypress" />

const invoiceTestcase01 = () => {

  cy.viewport(1920, 1080)
  cy.clearCookies()
  cy.clearLocalStorage()

  cy.visit('https://inventory.seebiz.cloud', {
    auth: {
      username: 'admin',
      password: 'Temp123'
    },
    timeout: 60000,
    failOnStatusCode: false
  })

  cy.loginIMS()
  cy.contains('Dashboard', { timeout: 20000 }).should('be.visible')
  cy.xpath("//button[@id='click_nav_arrow_button']").click()
  cy.xpath("//a[@id='click_invoice_module']").click()
  cy.xpath("//button[@id='Click_Add_New_Item_Adjustment_Button']").click()
  // ➕ ADD CUSTOMER
  cy.xpath("(//div[contains(@class,'indicatorContainer')])[1]").click()
  cy.wait(2000)
  cy.contains("Add New").should('be.visible').click()
  cy.wait(2000)

  // SELECT PREFIX
  cy.xpath("(//div[contains(@class,'searchable-dropdown__control')]//div[contains(@class,'searchable-dropdown__value-container')])[6]").click()
  cy.wait(3000)

  cy.get('div.searchable-dropdown__menu')
    .should('be.visible')
    .contains('Dr.')
    .click()

  // CREATE UNIQUE CUSTOMER
  const uniqueCustomerName = `CUSTOMER-${Date.now()}`
  cy.xpath("//input[@id='firstName']").clear().type(uniqueCustomerName)

  // SAVE CUSTOMER
  cy.xpath("(//div[@class='searchable-dropdown__control css-yk16xz-control'])[6]").click()
  cy.get('#react-select-11-option-0').click()

  cy.xpath("//button[contains(@type,'submit')][normalize-space()='Save']").click()
  cy.get('.toaster-body')
    .should('be.visible')
    .contains('Contact created successfully')

  // ADD NOTE
  cy.xpath("//textarea[@id='note']").type('THIS TEXT IS MANUALLY GENERATED BY THE QA TEAM')

  // ➕ ADD ITEM
  cy.xpath('(//div[@class=" css-tlfecz-indicatorContainer"])[3]').click()
  cy.wait(2000)

  cy.get('.DDTopElement').should('be.visible').contains('Add New').click()

  // IMAGE UPLOAD
  cy.get('input[type="file"]').attachFile('PROFILE.jpg')
  cy.xpath('//button[@id="next-btn"]').contains('Save Original').should('be.visible').click()

  // CREATE UNIQUE ITEM
  const uniqueItemName = `ITEM-${Date.now()}`
  cy.get('#name').clear().type(uniqueItemName)

  cy.xpath('(//input[@class="form-input"])[4]').click()
  cy.contains('kg').should('be.visible').click()
  cy.xpath('//button[@id="Click_generate_item_SKU"]').click()
  cy.xpath('//input[@id="purchaseUnitPrice"]').clear().type('100')
  cy.xpath('//input[@id="salesUnitPrice"]').clear().type('500')
  cy.xpath('//input[@id="warehouses[0].openingStock"]').clear().type('100')
  cy.xpath('//input[@id="openingStockValue"]').clear().type('10')
  cy.wait(2000)
  cy.xpath('(//button[@class="action-buttons--submit next-btn float-left"])[3]').contains('Save').should('be.visible').click()
  cy.xpath('//span[@class="total-price--value float-right mr-1"]').should('be.visible').contains('$500')
  // SAVE FINAL ITEM
  cy.xpath('//button[@type="button"]').contains('Save').should('be.visible').click()
  cy.wait(3000)
  cy.reload(true)
  cy.xpath('(//span[@class="list_items_desc"])[1]', { timeout: 30000 }).should('be.visible').click()
  // MARK ITEM AS SENT
  cy.xpath("//button[normalize-space()='Options']").click()
  cy.get('.checked-menu--dropdown .custom-dropdown-container:visible').contains('Mark as Sent').click()
  cy.reload(true)
  cy.xpath('(//span[@class="list_items_desc"])[1]').click()
  cy.get('.nav_menu > :nth-child(2) > a').click()
  cy.xpath('//button[@class="layout-box--button"]', { timeout: 20000 }).click()
  cy.xpath('//input[@id="amount"]').clear().click().type('500')
  cy.xpath('//button[@type="submit"]', { timeout: 20000 }).contains('Save').should('be.visible').click()
  cy.contains('a', 'Credit Notes').click()
  cy.xpath('//button[@class="layout-box--button"]', { timeout: 20000 }).click()
  cy.xpath("//span[normalize-space()='Add Credit Note']").should('contain.text', 'Add Credit Note')
  cy.xpath("//button[@type='submit' and normalize-space()='Save']").should('be.visible').click()
  cy.xpath("//div[@class='CaretDownButton']//*[name()='svg']").click()
  cy.xpath("//button[@type='submit' and normalize-space()='Mark as Open']").contains('Mark as Open').click()
  cy.xpath("//div[@class='CaretDownButton' and normalize-space()='Actions']").should('be.visible').click()
  cy.xpath("//div[contains(@class,'custom-dropdown-container down')]//span[contains(@class,'custom-dropdown-set')][normalize-space()='Edit']").contains('Edit').click()
  cy.xpath("//button[@type='submit' and normalize-space()='Save']").should('be.visible').click()
  cy.wait(3000)
  cy.reload()
  cy.xpath('//a[@class="ims-nav--link ims-nav--link active"]').should('be.visible').click()
  cy.xpath('//img[@id="currentOrg_logo"]').should('be.visible').click()
  cy.xpath('//button[@id="click_signout_button"]').should('be.visible').click()

}


//===================================Testcase 02====================================================================



const invoiceTestcase02 = () => {
  cy.viewport(1920, 1080)
  cy.clearCookies()
  cy.clearLocalStorage()

  cy.loginIMS()
  cy.xpath("//a[@id='click_invoice_module']").click()
  cy.xpath("//button[@id='Click_Add_New_Item_Adjustment_Button']").click()
  cy.xpath('//a[@class="ims-nav--link ims-nav--link active"]').click()
  cy.xpath('//button[@class="checked-menu--button button--primary float-left mr-3"]').click()
  cy.contains('Create Invoice').should('be.visible')

  cy.xpath("(//div[contains(@class,'indicatorContainer')])[1]").click()
  cy.wait(2000)
  cy.contains("Add New").should('be.visible').click()
  cy.wait(2000)

  // SELECT PREFIX
  cy.xpath("(//div[contains(@class,'searchable-dropdown__control')]//div[contains(@class,'searchable-dropdown__value-container')])[6]").click()
  cy.wait(3000)

  cy.get('div.searchable-dropdown__menu')
    .should('be.visible')
    .contains('Dr.')
    .click()

  // CREATE UNIQUE CUSTOMER
  const uniqueCustomerName = `CUSTOMER-${Date.now()}`
  cy.xpath("//input[@id='firstName']").clear().type(uniqueCustomerName)

  // SAVE CUSTOMER
  cy.xpath("(//div[@class='searchable-dropdown__control css-yk16xz-control'])[6]").click()
  cy.xpath('//div[@class="searchable-dropdown__option searchable-dropdown__option--is-focused css-1n7v3ny-option"]').click()
  cy.xpath("(//button[text()='Save'])[2]").click()
  cy.get(':nth-child(9) > .searchable-dropdown > .searchable-dropdown__control > .searchable-dropdown__indicators > .searchable-dropdown__indicator').click()
  cy.contains('EUR - € - Euro ').click()
  cy.xpath("//div[contains(@class,'css-1wa3eu0-placeholder') and contains(text(),'Select Items')]").click()
  cy.contains('IMS-258', { timeout: 20000 }).click()
  cy.xpath("//input[@value='0.00']").clear().type('100')
  cy.get('.switch-wrapper > :nth-child(1)').realClick()
  cy.xpath("//div[contains(text(),'Select Tax')]").realClick()
  cy.xpath('//input[@id="adjustment"]').type('121.25')
  cy.xpath('//input[@id="shippingCharge"]').type('565.88')
  cy.xpath('//button[@class="action-buttons--submit next-btn float-left"]').contains('Save').click()
  cy.xpath("//button[normalize-space()='Options']//*[name()='svg']").click()
  cy.xpath("//div[contains(@class,'custom-dropdown-container down')]//span[contains(@class,'custom-dropdown-set')][normalize-space()='Mark as Sent']").realClick()
  cy.get('.nav_menu > :nth-child(2) > a').click()
  cy.xpath('//button[@class="layout-box--button"]').click()
  cy.xpath("//button[normalize-space()='Save']").click()

  // Wait for the parent container
  cy.contains('Credit Notes', { timeout: 10000 }) // wait up to 10s
    .should('be.visible')
    .parent() // ya closest container jisme SVG ho
    .find('svg')
    .click()

  cy.xpath("//button[@class='layout-box--button']").click()
  cy.xpath("//button[normalize-space()='Save']").click()
  cy.xpath("//div[@class='CaretDownButton']").click()
  cy.xpath("//span[normalize-space()='Mark as Open']").click()
  cy.wait(3000)
  cy.reload()
  cy.xpath('//a[@class="ims-nav--link ims-nav--link active"]').should('be.visible').click()
  cy.xpath('//img[@id="currentOrg_logo"]').should('be.visible').click()
  cy.xpath('//button[@id="click_signout_button"]').should('be.visible').click()


}


//============================= Test Case 03===================================================


const invoiceTestcase03 = () => {
  cy.viewport(1920, 1080)
  cy.clearCookies()
  cy.clearLocalStorage()

  cy.loginIMS()
  cy.xpath('//a[@id="click_customer_payment_module"]').click()
  cy.xpath('//button[@class="checked-menu--button button--primary float-left mr-3"]').click()
  cy.xpath('//div[@class=" css-1wy0on6"]', { timeout: 20000 }).click()
  cy.xpath('//div[@class="DDTopElement"]', { timeout: 20000 }).click()

  // CREATE UNIQUE CUSTOMER
  const uniqueCustomerName = `CUSTOMER-${Date.now()}`
  cy.xpath("//input[@id='firstName']").clear().type(uniqueCustomerName)
  cy.xpath('(//div[@class="searchable-dropdown__indicators css-1wy0on6"])[4]').click()
  cy.xpath('(//div[@class="searchable-dropdown__option searchable-dropdown__option--is-focused css-1n7v3ny-option"])[1]').click()
  cy.xpath('//button[@class="action-buttons--submit next-btn float-left"]').click()
  cy.xpath('//input[@id="amount_received"]', { timeout: 20000 }).type('145.67')
  cy.xpath('//input[@id="reference"]').type('TRX-101')
  cy.xpath('//button[@class="dropdwon_with_button_button"]').click()
  cy.xpath("(//*[local-name()='svg' and @width='17' and @height='17'])[3]").click()
  cy.xpath('//button[@class="layout-box--button"]').click()

  //Assertions 
  cy.xpath('//div[@class="ims-modal--title  "]', { timeout: 20000 }).contains('Add Refund')
    .should('be.visible');
  //Assertions


  cy.contains('span', 'Total Available Amount')
    .invoke('text')
    .then(text => {

      const available = Number(text.replace(/[^0-9.]/g, ''));
      const enteredAmount = 9000; // jo bhi value test karni ho

      cy.get('#amount')
        .clear()
        .type(enteredAmount.toString());

      cy.get('#amount')
        .invoke('val')
        .then(val => {
          const actual = Number(val.replace(/[^0-9.]/g, ''));

          // 🔥 Golden Assertion (never breaks)
          expect(actual).to.be.at.most(available);
        });
    });

  cy.xpath('//button[@type="submit"]').contains('Save').click()
  cy.wait(5000)
  cy.reload({ force: true })
  cy.xpath('//a[@class="ims-nav--link ims-nav--link active"]').should('be.visible').click()
  cy.xpath('//img[@id="currentOrg_logo"]').should('be.visible').click()
  cy.xpath('//button[@id="click_signout_button"]').should('be.visible').click()

}


//============================= Test Case 04===================================================



const invoiceTestcase04 = () => {
  cy.viewport(1920, 1080)
  cy.clearCookies()
  cy.clearLocalStorage()

  cy.loginIMS()
  cy.xpath('(//*[local-name() = "svg" and @stroke-width="0" and @viewBox="0 0 24 24" and @height="1em"])[13]', { timeout: 20000 }).click()
  cy.xpath('//div[@class="top-header "]').contains('Create New Bills').should('be.visible')
  cy.xpath('(//div[@class=" css-1wa3eu0-placeholder"])[1]').click()
  cy.xpath('//div[@class="DDTopElement"]').click()

  cy.xpath('//div[@class="FileUploader_fileUploader__bpPfb undefined FileUploader_fileUploader_circle__3raX0"]')

  const uniquevendorName = `VENDOR-${Date.now()}`
  cy.xpath('//input[@id="firstName"]').type(uniquevendorName)

  cy.xpath('(//div[@class="searchable-dropdown__value-container css-1hwfws3"])[4]').click()
  cy.xpath('//div[@id="react-select-8-option-0"]').click()
  cy.get('input[type="file"]').attachFile('PROFILE.jpg')
  cy.xpath('//button[@id="next-btn"]').contains('Save Original').should('be.visible').click()
  cy.xpath('(//button[@class="action-buttons--submit next-btn float-left"])[2]').click()
  cy.xpath('(//div[@class=" css-1hwfws3"])[2]').click()
  cy.xpath('//div[@class="DDTopElement"]').click()
  cy.get('input[type="file"]').attachFile('PROFILE.jpg')
  cy.xpath('//button[@id="next-btn"]').contains('Save Original').should('be.visible').click()


  const uniqueitems = `ITEM-${Date.now()}`
  cy.xpath('//input[@id="name"]').type(uniqueitems)

  cy.xpath('(//input[@class="form-input"])[2]').click()
  cy.contains('kg').click()
  cy.xpath('//button[@id="Click_generate_item_SKU"]').click()
  cy.xpath('//INPUT[@id="purchaseUnitPrice"]').type('100')
  cy.xpath('//INPUT[@id="salesUnitPrice"]').type('500')
  cy.xpath('//INPUT[@id="warehouses[0].openingStock"]').type('100')
  cy.xpath('//INPUT[@id="openingStockValue"]').type('10')
  cy.xpath('//INPUT[@id="reorderLevel"]').type('02')


  cy.xpath('(//button[@class="action-buttons--submit next-btn float-left"])[2]').contains('Save').should('be.visible').click()
  cy.xpath('//input[@id="adjustment"]').type('1000')
  cy.xpath('//button[@class="action-buttons--submit next-btn float-left"]', { timeout: 20000 }).contains('Save').click()
  cy.xpath("(//*[name()='svg' and @viewBox='0 0 20 20' and @fill='none' and @width='20'])[10]").closest('button, div, [role="button"]').scrollIntoView().click()

  cy.xpath("//div[contains(@class,'custom-dropdown-container down')]//span[@class='custom-dropdown-set'][normalize-space()='Mark as Open']").click()
  cy.reload()
  cy.xpath("//a[normalize-space()='Payments']", { timeout: 20000 }).contains("Payments").should('be.visible').click()

  cy.xpath('//button[@class="layout-box--button"]').click()
  cy.xpath('(//button[@class="action-buttons--submit next-btn float-left"])[1]').contains('Save').click()
  cy.xpath('//div[@class="payment_view"]').click()
  cy.xpath('//span[@class="close-button"]').click()
  cy.wait(3000)
  cy.reload()
  cy.xpath('//a[@class="ims-nav--link ims-nav--link active"]').should('be.visible').click()
  cy.xpath('//img[@id="currentOrg_logo"]').should('be.visible').click()
  cy.xpath('//button[@id="click_signout_button"]').should('be.visible').click()

}


//============================= Test Case 05===================================================

const invoiceTestcase05 = () => {
  cy.viewport(1920, 1080)
  cy.clearCookies()
  cy.clearLocalStorage()

  cy.loginIMS()
  cy.xpath('(//span[@class="ims-nav-menu-icon"])[2]').click()
  cy.xpath("//a[@href='/item-groups/add']//*[local-name()='svg' and @fill='currentColor' and @stroke='currentColor']", { timeout: 20000 }).click()
  cy.get('input[type="file"]').attachFile('PROFILE.jpg')
  cy.xpath('//button[@id="next-btn"]').contains('Save Original').should('be.visible').click()
  const uniqueitems = `ITEM-${Date.now()}`
  cy.xpath('//input[@id="name"]').type(uniqueitems)
  cy.xpath('(//input[@class="form-input"])[1]').click()
  cy.contains('kg').click()
  cy.xpath('//input[@id="manufacturer"]').type('SeeBiz')
  cy.xpath('//input[@id="brand"]').type('Uniliver')
  cy.xpath('//textarea[@id="description"]').type('THIS TEXT IS MANUALLY GENERATED BY THE QA TEAM')
  cy.xpath('(//div[@class="searchable-dropdown__indicator searchable-dropdown__dropdown-indicator css-tlfecz-indicatorContainer"])[1]').click()
  cy.xpath('//div[@class="DDTopElement"]').click()


  const uniquetaxname = `TAX-${Date.now()}`
  cy.xpath('(//input[@id="name"])[2]').type(uniquetaxname)

  cy.xpath('//input[@id="rate"]').type('10')
  cy.xpath('//input[@id="authority"]').type('GOVERNMENT')
  cy.xpath('(//button[@class="action-buttons--submit next-btn float-left"])[2]').click()
  cy.xpath('(//input[@class="form-input"])[4]').click()
  cy.xpath('//div[@class="auto-complete--suggestion"]').contains('Size').click()
  cy.xpath('//div[@class="select__value-container select__value-container--is-multi css-1hwfws3"]').type('38{enter}').type('37{enter}').type('36{enter}')
  cy.xpath('//button[@class="attribute_btn float-left w-100 group-btn-sm"]').contains('Generate SKU').click()
  cy.xpath('//input[@id="itemsList[0].costPrice"]').type('1000')
  cy.xpath('(//span[@class="popover__title  group-btn-sm"])[1]').contains('Copy to all').click()
  cy.xpath('(//button[@class="next-btn"])[1]').contains('Yes').click()
  cy.xpath('//input[@id="itemsList[0].sellingPrice"]').type('2000')
  cy.xpath('(//span[@class="popover__title  group-btn-sm"])[2]').contains('Copy to all').click()
  cy.xpath('(//button[@class="next-btn"])[2]').contains('Yes').click()
  cy.xpath('//input[@id="itemsList[0].reorderPoint"]').type('02')
  cy.xpath('(//span[@class="popover__title  group-btn-sm"])[3]').contains('Copy to all').click()
  cy.xpath('(//button[@class="next-btn"])[3]').contains('Yes').click()
  cy.xpath('//button[@class="action-buttons--submit next-btn float-left"]').click()
  cy.xpath('(//input[@id="itemsList[0].warehouses[0].openingStock"])[1]').type('100')
  cy.xpath('//div[@class="popover__wrapper attribute_btn float-left w-100 group-btn-sm item-group-add"]').contains('Copy to all').should('be.visible').click()
  cy.xpath('//div[@class="popover__message"]').contains('Would you like 100 amount to be reflected in all below field').should('be.visible')
  cy.xpath('//button[@class="next-btn"]').contains('Yes').should('be.visible').click()
  cy.xpath('//button[@class="action-buttons--submit next-btn float-left"]').contains('Save').should('be.visible').click()
  cy.wait(5000)
  cy.reload()
  cy.xpath('//a[@class="ims-nav--link ims-nav--link active"]').should('be.visible').click()
  cy.xpath('//img[@id="currentOrg_logo"]').should('be.visible').click()
  cy.xpath('//button[@id="click_signout_button"]').should('be.visible').click()


}


//============================= Test Case 06===================================================

const invoiceTestcase06 = () => {
  cy.viewport(1920, 1080)
  cy.clearCookies()
  cy.clearLocalStorage()

  cy.loginIMS()
  cy.xpath('//button[@title="Items"]', { timeout: 20000 }).click()
  cy.xpath("(//*[local-name()='svg' and @stroke='currentColor' and @fill='currentColor'])[6]", { timeout: 20000 }).click()

  cy.get('input[type="file"]').attachFile('PROFILE.jpg')
  cy.xpath('//button[@id="next-btn"]').contains('Save Original').should('be.visible').click()

  const allitems = `New-Item-${Date.now()}`
  cy.xpath('//input[@id="name"]').type(allitems)

  cy.xpath('(//input[@class="form-input"])[2]').click()
  cy.xpath('//li[@id="react-autowhatever-1--item-0"]', { timeout: 20000 }).contains('kg').should('be.visible').click()
  cy.xpath('//button[@class="button form-field--side-btn"]').contains('Generate SKU').should('be.visible').click()

  const last4Digits = Date.now().toString().slice(-4)

  const upcnumber = `UPC-${last4Digits}`
  cy.xpath('//input[@id="upc"]').type(upcnumber)

  const mpnnumber = `MPN-${last4Digits}`
  cy.xpath('//input[@id="mpn"]').type(mpnnumber)

  const eannumber = `EAN-${last4Digits}`
  cy.xpath('//input[@id="ean"]').type(eannumber)

  const isbnnumber = `ISBN-${last4Digits}`
  cy.xpath('//input[@id="isbn"]').type(isbnnumber)

  const Description02 = `THIS-TEXT-IS-MANUALLY-GENERATED-BY-THE-QA-TEAM-${last4Digits}`
  cy.xpath('//textarea[@id="description"]').type(Description02)

  cy.xpath('//input[@id="manufacturer"]').type('UNILIVER')
  cy.xpath('//input[@id="brand"]').type('SEEBIZ')
  cy.xpath('//input[@id="weight"]').type('100kg')
  cy.xpath('//input[@id="purchaseUnitPrice"]').type('100')
  cy.xpath('//input[@id="salesUnitPrice"]').type('500')
  cy.xpath('//textarea[@id="purchaseDescription"]').type('THIS TEXT IS MANUALLY GENERATED BY THE QA TEAM')
  cy.xpath('//textarea[@id="salesDescription"]').type('THIS TEXT IS MANUALLY GENERATED BY THE QA TEAM')
  cy.xpath('(//div[@class="searchable-dropdown__value-container css-1hwfws3"])[2]').click()
  cy.xpath('//div[@class="DDTopElement"]').click()


  const taxname = `Tax-${Date.now()}`
  cy.xpath('(//input[@class="form-input"])[11]').type(taxname)

  cy.xpath('//input[@id="rate"]').type('15')
  cy.xpath('//input[@id="authority"]').type('GOVERNMENT')
  cy.xpath('(//button[@type="submit"])[14]').click()
  cy.xpath('(//button[@type="button"])[5]').click()
  cy.wait(3000)
  cy.reload()
  cy.xpath('//a[@class="ims-nav--link ims-nav--link active"]').should('be.visible').click()
  cy.xpath('//img[@id="currentOrg_logo"]').should('be.visible').click()
  cy.xpath('//button[@id="click_signout_button"]').should('be.visible').click()

}


//==========================Test Case 07===================================================

const invoiceTestcase07 = () => {
  cy.viewport(1920, 1080)
  cy.clearCookies()
  cy.clearLocalStorage()

  cy.loginIMS()
  cy.xpath('//button[@title="Items"]', { timeout: 20000 }).click()
  cy.xpath("(//*[local-name()='svg' and @stroke='currentColor' and @viewBox='0 0 24 24' and @class='ims-nav--add-icon'])[3]", { timeout: 20000 }).click()
  cy.xpath('//textarea[@id="reason"]').type('Defective Item')
  cy.xpath('//textarea[@id="description"]').type('THIS TEXT IS MANUALLY GENERATED BY THE QA TEAM')
  cy.xpath('//div[@class=" css-1hwfws3"]').click()
  cy.xpath('(//div[@class="desc"])[1]').click()
  cy.xpath('//input[@id="items[0].adjustedQuantity"]').dblclick().type('10')
  cy.xpath('//button[@class="action-buttons--submit next-btn float-left"]').contains('Save').click()
  cy.wait(3000)
  cy.reload()
  cy.xpath('//a[@class="ims-nav--link ims-nav--link active"]').should('be.visible').click()
  cy.xpath('//img[@id="currentOrg_logo"]').should('be.visible').click()
  cy.xpath('//button[@id="click_signout_button"]').should('be.visible').click()

}


//==========================Test Case 08===================================================


const invoiceTestcase08 = () => {
  cy.viewport(1920, 1080)
  cy.clearCookies()
  cy.clearLocalStorage()

  cy.loginIMS()
  cy.xpath("(//*[local-name()='svg' and @stroke='currentColor' and @fill='currentColor'])[8]", { timeout: 20000 }).click()
  cy.xpath('(//div[@class="searchable-dropdown__value-container css-1hwfws3"])[1]').click()

  const uniqueCustomerName = `CUSTOMER-${Date.now()}`
  cy.xpath('//input[@id="firstName"]').type(uniqueCustomerName)


  const companyname = `COMPANY-${Date.now()}`
  cy.xpath('//input[@id="companyName"]').type(companyname)

  cy.xpath('(//div[@class="searchable-dropdown__value-container css-1hwfws3"])[2]').click()
  cy.xpath('//div[@class="searchable-dropdown__option css-yt9ioa-option"]').click()
  cy.xpath('(//div[@class="searchable-dropdown__indicators css-1wy0on6"])[4]').click()
  cy.xpath('(//div[@class="searchable-dropdown__option css-yt9ioa-option"])[1]').click()
  cy.xpath('//input[@id="workPhone"]').type('1234567890')
  cy.xpath('//input[@id="mobile"]').type('1234567890')
  cy.xpath('//input[@id="workPhone_secondary"]').type('1234567890')
  cy.xpath('//button[@class="action-buttons--submit next-btn float-left"]').contains('Save').click()
  cy.xpath("//a[normalize-space()='Activity']").click()
  cy.xpath("(//*[local-name()='svg' and @stroke='currentColor' and @fill='currentColor' and @height='1em'])[16]").click()
  cy.xpath('(//a[@class="custom-dropdown--options"])[10]').contains('Clone').should('be.visible').click()
  cy.xpath('(//div[@class="searchable-dropdown__value-container css-1hwfws3"])[1]').click()
  cy.xpath('(//div[@class="searchable-dropdown__value-container css-1hwfws3"])[1]').dblclick()
  cy.contains('Dr.').should('be.visible').click()


  const CloneName = `CUSTOMER-${Date.now()}`
  cy.xpath('//input[@id="firstName"]').type(CloneName)

  cy.xpath('//div[@class="searchable-dropdown__value-container css-1hwfws3"]').click()
  cy.xpath('(//div[@class="searchable-dropdown__option css-yt9ioa-option"])[1]').click()
  cy.xpath('//button[@class="action-buttons--submit next-btn float-left"]').click()
  cy.wait(3000)
  cy.xpath('//a[@class="ims-nav--link ims-nav--link active"]').should('be.visible').click()
  cy.xpath('//img[@id="currentOrg_logo"]').should('be.visible').click()
  cy.xpath('//button[@id="click_signout_button"]').should('be.visible').click()

}

//==========================Test Case 09===================================================

const invoiceTestcase09 = () => {
  cy.viewport(1920, 1080)
  cy.clearCookies()
  cy.clearLocalStorage()

  cy.loginIMS()
  cy.xpath('//button[@title="Items"]', { timeout: 20000 }).click()
  cy.xpath('(//a[@class="ims-nav--link-add"])[9]').click()
  cy.xpath('(//div[@class=" css-1wy0on6"])[1]').click()
  cy.xpath('//div[@class="DDTopElement"]').click()

  const uniqueCustomerName = `CUSTOMER-${Date.now()}`
  cy.xpath('//input[@id="firstName"]').type(uniqueCustomerName)
  const companyname = `COMPANY-${Date.now()}`
  cy.xpath('//input[@id="companyName"]').type(companyname)

  cy.xpath('//input[@id="workPhone"]').type('1234567890')
  cy.xpath('//input[@id="mobile"]').type('1234567890')
  cy.xpath('//input[@id="workPhone_secondary"]').type('1234567890')
  cy.xpath('(//div[@class="searchable-dropdown__indicators css-1wy0on6"])[5]').realClick()
  cy.xpath('//div[@class="searchable-dropdown__option searchable-dropdown__option--is-focused css-1n7v3ny-option"]').realClick()
  cy.xpath('//button[@class="action-buttons--submit next-btn float-left"]').contains('Save').click()
  cy.xpath('//input[@id="reference"]').click().type('TRX-101')
  cy.xpath('(//DIV[@class=" css-1hwfws3"])[2]', { timeout: 20000 }).realClick()
  cy.xpath('//div[@class="DDTopElement"]').click()

  const UNIQUEITEMNAME = `ITEM-${Date.now()}`
  cy.xpath('//input[@id="name"]').type(UNIQUEITEMNAME)

  cy.xpath('(//input[@class="form-input"])[4]').click()
  cy.xpath('(//div[@class="auto-complete--suggestion"])[1]', { timeout: 20000 }).contains('kg').should('be.visible').click()

  cy.xpath('//button[@class="button form-field--side-btn"]').click()

  const last4Digits = Date.now().toString().slice(-4)

  const upcnumber = `UPC-${last4Digits}`
  cy.xpath('//input[@id="upc"]').type(upcnumber)

  const mpnnumber = `MPN-${last4Digits}`
  cy.xpath('//input[@id="mpn"]').type(mpnnumber)

  const eannumber = `EAN-${last4Digits}`
  cy.xpath('//input[@id="ean"]').type(eannumber)

  const isbnnumber = `ISBN-${last4Digits}`
  cy.xpath('//input[@id="isbn"]').type(isbnnumber)

  const Description02 = `THIS-TEXT-IS-MANUALLY-GENERATED-BY-THE-QA-TEAM-${last4Digits}`
  cy.xpath('//textarea[@id="description"]').type(Description02)


  cy.xpath('//input[@id="manufacturer"]').type('UNILIVER')
  cy.xpath('//input[@id="brand"]').type('SEEBIZ')
  cy.xpath('//input[@id="weight"]').type('100kg')
  cy.xpath('//input[@id="purchaseUnitPrice"]').type('100')
  cy.xpath('//input[@id="salesUnitPrice"]').type('500')
  cy.xpath('//textarea[@id="purchaseDescription"]').type('THIS TEXT IS MANUALLY GENERATED BY THE QA TEAM')
  cy.xpath('//textarea[@id="salesDescription"]').type('THIS TEXT IS MANUALLY GENERATED BY THE QA TEAM')
  cy.xpath('(//div[@class="searchable-dropdown__value-container css-1hwfws3"])[4]').click()
  cy.xpath('//div[@class="searchable-dropdown__option searchable-dropdown__option--is-focused css-1n7v3ny-option"]').click()
  cy.xpath('//input[@id="warehouses[0].openingStock"]').type('100')
  cy.xpath('//input[@id="openingStockValue"]').type('10')
  cy.xpath('//input[@id="reorderLevel"]').type('02')
  cy.xpath('//button[@class="action-buttons--submit next-btn float-left"]').click()
  cy.wait(3000)
  cy.reload()
  cy.xpath('//a[@class="ims-nav--link ims-nav--link active"]').should('be.visible').click()
  cy.xpath('//img[@id="currentOrg_logo"]').should('be.visible').click()
  cy.xpath('//button[@id="click_signout_button"]').should('be.visible').click()

}



//==========================Test Case 10===================================================

const invoiceTestcase10 = () => {
  cy.viewport(1920, 1080)
  cy.clearCookies()
  cy.clearLocalStorage()

  cy.loginIMS()
  cy.xpath('(//button[@class="ims-nav--item-button"])[3]').click()
  cy.xpath('//span[@class="ims-nav-menu-subtext manage_oraganization_btn "]').click()
  cy.xpath('//button[@class="button--primary float-left mr-3"]').click()

  const Organizationname = `ORG-${Date.now()}`
  cy.xpath('//input[@id="organizationName"]').type(Organizationname)

  cy.xpath('(//div[@class="searchable-dropdown__indicators css-1wy0on6"])[1]').click()
  cy.xpath('//div[@id="react-select-2-option-3"]').click()
  cy.xpath('(//div[@class="searchable-dropdown__indicators css-1wy0on6"])[2]').click()
  cy.xpath('//div[@id="react-select-3-option-1"]').click()
  cy.xpath('(//div[@class="searchable-dropdown__indicators css-1wy0on6"])[3]').click()
  cy.xpath('//div[@id="react-select-4-option-0" and @tabindex="-1"]').click()
  cy.xpath('(//div[@class="searchable-dropdown__indicators css-1wy0on6"])[4]').click()
  cy.xpath('//div[@id="react-select-5-option-120"]').click()
  cy.xpath('//input[@id="license_no"]').type('TRX-9812')
  cy.xpath('//input[@id="primaryContactName"]').type('Haseeb Pirzaada')

  cy.xpath('//input[@id="organizationStreet"]').type('House No 22 | Street 06 | Lane 05 | Phase 02 | Wapda Town Lahore')


  const primaryContactEmail = `New${Date.now()}@example.com`
  cy.xpath('//input[@id="primaryContactEmail"]').type(primaryContactEmail)
  cy.xpath('//input[@id="organizationCity"]').type('Lahore')
  cy.xpath('//input[@id="organizationProvince"]').type('Punjab')
  cy.xpath('//input[@id="organizationPostalCode"]').type('10001')
  cy.xpath('(//div[@class="searchable-dropdown__indicators css-1wy0on6"])[6]').click()
  cy.contains('United States').click()
  cy.xpath('//input[@placeholder="Phone"]').type('1234567890')
  cy.xpath('//input[@id="organizationWebsite"]').type('https://inventory.seebiz.cloud/organization/add')
  cy.xpath('//button[@class="action-buttons--submit next-btn float-left"]').click()
  cy.wait(5000)
  cy.get('.top-header').contains('Settings - Manage Businesses', {timeout:20000}).should('be.visible')
  cy.reload()

}



//==========================Test Case 10===================================================


const invoiceTestcase11 = () => {
  cy.viewport(1920, 1080)
  cy.clearCookies()
  cy.clearLocalStorage()

  cy.loginIMS()

}




export {
  invoiceTestcase01,
  invoiceTestcase02,
  invoiceTestcase03,
  invoiceTestcase04,
  invoiceTestcase05,
  invoiceTestcase06,
  invoiceTestcase07,
  invoiceTestcase08,
  invoiceTestcase09,
  invoiceTestcase10,
  invoiceTestcase11
}
